---
   interfaces:
      interface_0:
           desc: wan
           number: 0
           ip: 10.60.221.64 
           mask: 255.255.255.192
      interface_30:
           desc: wlan
           number: 0.30
           ip: 10.225.87.225
           mask: 255.255.255.248
   wan_ip: 10.177.124.1
   peers:
      networks_1:
         net: 10.60.221.64
         mask: 255.255.255.192   
      networks_2:
         net: 10.225.87.224
         mask: 255.255.255.224
